export const constant_townVersion: string = "4.11"
export const constant_patchLink: string ="season-3-update"
export const constant_questXP: number = 100
export const constant_questGold: number = 100
export const questWin_xpMultiplier: number = 1.5
export const questLoss_xpMultiplier: number = .5
export const questWin_goldMultiplier: number = 1
export const questLoss_goldMultiplier: number = 0
export const constant_spiritVesselMultiplier: number = 0.5
export const questWin_etherealBladeMultiplier: number = 10
export const questLoss_etherealBladeMultiplier: number = 1
export const constant_OrchidMultiplier: number = 0.5